import type { StandardResume } from '../../types/resume';

export const EMPTY_RESUME: StandardResume = {
  id: 'resume-default',
  title: '我的求职档案',
  isDefault: true,
  createdAt: Date.now(),
  updatedAt: Date.now(),
  schemaVersion: 3,
  basics: {
    name: '',
    firstName: '',
    lastName: '',
    middleName: '',
    preferredName: '',
    gender: '',
    birthDate: '',
    phone: '',
    email: '',
    avatarUrl: '',
    idCardType: '',
    idCardNumber: '',
    politicalStatus: '',
    ethnicity: '',
    maritalStatus: '',
    height: '',
    weight: '',
    healthStatus: '',
    country: 'China',
    state: '',
    postalCode: '',
    addressLine1: '',
    addressLine2: '',
    nativePlace: { province: '', city: '', district: '', detail: '' },
    currentLocation: { province: '', city: '', district: '', detail: '' },
    hukouLocation: { province: '', city: '', district: '', detail: '' },
    workingYears: 0,
    jobStatus: '',
    expectedRole: '',
    expectedCity: '',
    githubUrl: '',
    linkedinUrl: '',
    blogUrl: '',
    portfolioUrl: '',
    selfEvaluation: '',
  },
  educations: [],
  experiences: [],
  projects: [],
  skills: [],
  languages: [],
  certificates: [],
  familyMembers: [],
  qaBank: [],
};

export const DEMO_RESUME: StandardResume = {
  id: 'demo-resume-1',
  title: '示例简历 (张三 - 前端开发)',
  isDefault: true,
  createdAt: Date.now(),
  updatedAt: Date.now(),
  schemaVersion: 3,
  basics: {
    name: '张三',
    gender: '男',
    birthDate: '2001-05-18',
    age: 24,
    phone: '13800138000',
    email: 'zhangsan@example.com',
    avatarUrl: '',
    idCardType: '身份证',
    idCardNumber: '110101200105182345',
    politicalStatus: '共青团员',
    ethnicity: '汉族',
    maritalStatus: '未婚',
    height: '178',
    weight: '68',
    healthStatus: '健康',
    nativePlace: {
      province: '北京市',
      city: '北京市',
      district: '海淀区',
      detail: '中关村南大街1号',
    },
    currentLocation: {
      province: '北京市',
      city: '北京市',
      district: '海淀区',
      detail: '知春路56号',
    },
    hukouLocation: {
      province: '北京市',
      city: '北京市',
    },
    workingYears: 0,
    jobStatus: '应届毕业生',
    expectedRole: '前端开发工程师',
    expectedCity: '北京',
    expectedSalaryMin: 18,
    expectedSalaryMax: 30,
    availableTime: '随时',
    githubUrl: 'https://github.com/example-zhangsan',
    linkedinUrl: 'https://www.linkedin.com/in/example-zhangsan',
    blogUrl: 'https://blog.example.com',
    portfolioUrl: 'https://portfolio.example.com',
    selfEvaluation: '精通现代化前端技术栈（Vue 3、React、TypeScript），具备大型复杂单页应用及高并发组件架构设计经验；深入理解浏览器渲染机制与性能优化；做事严谨，具有良好的团队沟通与开源协作精神。',
  },
  educations: [
    {
      id: 'edu-1',
      schoolName: '北京航空航天大学',
      degree: '硕士',
      degreeEn: 'Master',
      major: '计算机科学与技术',
      majorCategory: '工学',
      college: '计算机学院',
      startDate: '2023-09',
      endDate: '2026-06',
      gpa: '3.85/4.0',
      ranking: '前 5%',
      isFullTime: true,
      isHighest: true,
      is985_211: true,
      courses: '高级计算机体系结构、分布式系统、机器学习与算法设计',
      awards: '国家一等学业奖学金、校优秀研究生',
    },
    {
      id: 'edu-2',
      schoolName: '北京航空航天大学',
      degree: '本科',
      degreeEn: 'Bachelor',
      major: '软件工程',
      majorCategory: '工学',
      college: '软件学院',
      startDate: '2019-09',
      endDate: '2023-06',
      gpa: '3.78/4.0',
      ranking: '前 10%',
      isFullTime: true,
      isHighest: false,
      is985_211: true,
      courses: '数据结构、操作系统、编译原理、计算机网络、数据库系统原理',
      awards: '国家励志奖学金、ACM-ICPC 区域赛铜奖',
    },
  ],
  experiences: [
    {
      id: 'exp-1',
      company: '某知名互联网科技公司',
      department: '基础架构部',
      title: '前端研发实习生',
      jobType: '实习',
      city: '北京',
      startDate: '2024-06',
      endDate: '2025-02',
      isCurrent: false,
      description: '负责中台微前端架构演进与低代码表单渲染引擎核心模块开发；重构核心业务看板，通过虚拟滚动与 Web Worker 数据解析将首屏加载耗时从 2.8s 降低至 0.9s。',
      achievements: '主导完成低代码组件协议制定，赋能 20+ 业务线快速上线。',
      techStack: 'Vue 3, TypeScript, Vite, TailwindCSS, Web Worker',
      witnessName: '李经理',
      witnessPhone: '13900139000',
    },
  ],
  projects: [
    {
      id: 'proj-1',
      projectName: '企业级低代码可视化表单与工作流设计器',
      role: '核心开发者',
      startDate: '2024-03',
      endDate: '2024-11',
      projectUrl: 'https://github.com/example/lowcode-designer',
      description: '面向企业协同办公场景的低代码流程与动态表单搭建平台，支持拖拽布局、复合校验逻辑与跨平台渲染。',
      responsibility: '设计基于 JSON Schema 的动态表单渲染内核与撤销重做历史栈，实现自定义公式计算与动态联动机制。',
      techStack: 'Vue 3, Pinia, TypeScript, Canvas, Node.js',
      achievements: '在 GitHub 斩获 1.2k+ Star，支撑部门超 50 种审批表单无代码交付。',
    },
    {
      id: 'proj-2',
      projectName: '高性能 Chrome 扩展自动化助手',
      role: '项目独立设计与开发',
      startDate: '2024-12',
      endDate: '2025-03',
      projectUrl: 'https://github.com/example/auto-helper',
      description: '基于 Manifest V3 标准构建的浏览器自动化与辅助填表工具，适配主流 ATS 系统与现代 SPA 框架。',
      responsibility: '全流程负责架构设计、DOM 启发式匹配算法实现及 Shadow DOM UI 隔离。',
      techStack: 'TypeScript, WXT, Vue 3, Shadow DOM, TailwindCSS',
      achievements: '实现 98% 字段匹配准确率与跨平台秒级回填。',
    },
  ],
  languages: [
    {
      id: 'lang-1',
      language: '英语',
      proficiency: '熟练',
      certificateName: 'CET-6',
      score: '612',
    },
    {
      id: 'lang-2',
      language: '英语',
      proficiency: '熟练',
      certificateName: 'IELTS (雅思)',
      score: '7.5',
    },
  ],
  skills: [
    { id: 'skill-1', name: 'JavaScript / TypeScript', level: '精通' },
    { id: 'skill-2', name: 'Vue 3 / React 生态', level: '精通' },
    { id: 'skill-3', name: '前端工程化与性能优化 (Vite, Webpack)', level: '熟练' },
    { id: 'skill-4', name: 'Node.js / Express / NestJS', level: '熟练' },
    { id: 'skill-5', name: 'Git / CI/CD / Docker 基础', level: '熟悉' },
  ],
  certificates: [
    { id: 'cert-1', name: '大学英语六级 (CET-6)', issueDate: '2022-06' },
    { id: 'cert-2', name: '计算机技术与软件专业技术资格（高级系统分析师）', issueDate: '2023-11' },
  ],
  familyMembers: [
    {
      id: 'fam-1',
      relation: '父亲',
      name: '张建国',
      company: '北京市某工程技术有限公司',
      jobTitle: '高级工程师',
      phone: '13700137000',
      politicalStatus: '中共党员',
    },
    {
      id: 'fam-2',
      relation: '母亲',
      name: '王淑芬',
      company: '北京市某中学',
      jobTitle: '教师',
      phone: '13600136000',
      politicalStatus: '群众',
    },
  ],
  qaBank: [
    {
      id: 'qa-1',
      keyword: '自我评价',
      answer: '具备扎实的计算机科学与前端工程基础，学习能力强，热衷钻研前沿技术并转化为业务生产力。具备良好的抗压能力与沟通协作意识。',
    },
    {
      id: 'qa-2',
      keyword: '为什么加入我们',
      answer: '贵公司在行业内拥有领先的技术视野与卓越的产品影响力，我一直非常关注贵公司的技术动态。我的专业背景与实践经验高度契合该岗位的要求，渴望能在这个优秀的平台上共同创造价值。',
    },
    {
      id: 'qa-3',
      keyword: '职业规划',
      answer: '短期内（1-2年）快速深入业务场景，成为团队中能独当一面的技术骨干；中期（3-5年）深耕前端底层架构与工程效能，成为兼具业务理解与技术深度的全栈/架构专家。',
    },
  ],
};

export const DEFAULT_RESUME: StandardResume = EMPTY_RESUME;
